apiVersion: v1
kind: Service
metadata:
  name: guacamole
  labels:
    app: guacamole
spec:

  type: LoadBalancer
  loadBalancerIP: 35.225.46.49
  externalTrafficPolicy: Local    
    
  selector:
    app: guacamole

  ports:
  
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: ui 

